aggregate status of tasks
Implementing TEP-0049, it is now possible to access aggregate execution
status of all tasks using `$(tasks.status)`. This context variable is
only available in a finally task.

diff --git a/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml b/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml
--- a/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml
+++ b/examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml
@@ -42,3 +42,17 @@ spec:
               if [[ $(params.task1Status) != "Succeeded" ||  $(params.task2Status) != "None" ]]; then
                 exit 1;
               fi
+    - name: task4 # this task verifies the aggregate status of all tasks, it fails if verification fails
+      params:
+        - name: aggregateStatus
+          value: "$(tasks.status)"
+      taskSpec:
+        params:
+          - name: aggregateStatus
+        steps:
+          - image: alpine
+            name: verify-aggregate-tasks-status
+            script: |
+              if [[ $(params.aggregateStatus) != "Completed" ]]; then
+                exit 1;
+              fi
