updating a taskrun with array parameters
Updating a taskrun to check the length of each array and also validate
the elements of the array instead of just echoing the expected values.

Also, updating a doc with the specification on how to specify array params
and object params.

Signed-off-by: pritidesai <pdesai@us.ibm.com>

diff --git a/examples/v1beta1/taskruns/array-default.yaml b/examples/v1beta1/taskruns/array-default.yaml
--- a/examples/v1beta1/taskruns/array-default.yaml
+++ b/examples/v1beta1/taskruns/array-default.yaml
@@ -25,8 +25,39 @@ spec:
       - name: echo-params
         image: bash:3.2
         args: [
-          "echo",
           "$(params.array-to-echo[*])",
           "$(params.another-array-to-echo[*])",
           "$(params.string-to-echo)",
         ]
+        script: |
+          #!/usr/bin/env bash
+          if [[ $# != 5 ]]; then
+            echo "failed to validate the length of the arguments"
+            echo "Want: 5, Got: $#"
+            exit 1
+          fi
+          if [[ $1 != "foo" ]]; then
+            echo "failed to validate the first argument to the script"
+            echo "Want: foo, Got: $1"
+            exit 1
+          fi
+          if [[ $2 != "bar" ]]; then
+            echo "failed to validate the second argument to the script"
+            echo "Want: bar, Got: $2"
+            exit 1
+          fi
+          if [[ $3 != "foo-default" ]]; then
+            echo "failed to validate the third argument to the script"
+            echo "Want: foo-default, Got: $3"
+            exit 1
+          fi
+          if [[ $4 != "bar-default" ]]; then
+            echo "failed to validate the fourth argument to the script"
+            echo "Want: bar-default, Got: $4"
+            exit 1
+          fi
+          if [[ $5 != "baz" ]]; then
+            echo "failed to validate the fifth argument to the script"
+            echo "Want: baz, Got: $5"
+            exit 1
+          fi
