Lockdown /tekton/step folders to their own steps.
This change symlinks /tekton/step folders to a step's corresponding /tekton/run folder.
This is an incremental change to lock down the /tekton folder to prevent tampering
of exitCode files from other steps.
Note: this does not completely protect against a step from tampering from its own
output - more work will needed in a future PR to fully lock this down, but this
is a step in the right direction (and a complete fix will likely require a more
involved design).

While /tekton/steps is now considered an implementation detail and could
potentially be removed, the folder is preserved for now to limit the scope of this PR.

- Moves `exitCode` output to `/tekton/run/<step #>/status`
- Symlinks `/tekton/steps/<step #>` and `/tekton/steps/<step name>` to
`/tekton/run/<step #>/status`.
- Creates new `tekton-init` entrypoint subcommand to initialize the
Tekton step directory.
- Removes `-step_metadata_dir_link` flag from the main entrypoint binary
(this behavior is now handled by the initcontainer).

Co-authored-by: Lee Bernick <leebernick@google.com>

diff --git a/examples/v1beta1/taskruns/readonly-internal-dir.yaml b/examples/v1beta1/taskruns/readonly-internal-dir.yaml
--- a/examples/v1beta1/taskruns/readonly-internal-dir.yaml
+++ b/examples/v1beta1/taskruns/readonly-internal-dir.yaml
@@ -19,3 +19,13 @@ spec:
           echo "able to write to run directory of non-current step"
           exit 1
         fi
+    - image: ubuntu
+      script: |
+        set +e # dont fail the script on error
+
+        # Steps should not be able to write to other step's step directories.
+        echo "hello world" > /tekton/steps/0/exitCode
+        if [ $? -eq 0 ] ; then
+          echo "able to write to run directory of non-current step"
+          exit 1
+        fi
