show logs for failures Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

diff --git a/.github/workflows/kind-e2e.yaml b/.github/workflows/kind-e2e.yaml
--- a/.github/workflows/kind-e2e.yaml
+++ b/.github/workflows/kind-e2e.yaml
@@ -92,7 +92,13 @@ jobs:
         sleep 2
 
         echo "Waiting for the pipelinerun to complete..."
-        kubectl wait --timeout 3m --for=condition=Succeeded pipelineruns --all || kubectl get taskruns -o yaml
+        if ! kubectl wait --timeout 3m --for=condition=Succeeded pipelineruns --all ; then
+          kubectl get taskruns -oyaml
+          kubectl get pipelineruns -oyaml
+          echo "Pipelinerun failed to complete in time"
+          ./tkn pipelinerun logs demo.pipeline -a -n default
+          exit 1
+        fi
 
     - name: Collect diagnostics
       if: ${{ failure() }}
